{{- if .Values.ui.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "spinnaker.fullname" . }}-deck
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "spinnaker.fullname" . }}
    component: deck
  annotations:
{{ toYaml .Values.ui.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ui.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.ui.ingress.hosts }}
      - {{ . }}
      {{- end }}
      secretName: {{ .Values.ui.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- $ctx := . }}
    {{- range .Values.ui.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: {{ template "spinnaker.fullname" $ctx }}-deck
              servicePort: {{ $.Values.ui.port }}
    {{- end -}}
{{- end -}}
