{{ if .Values.providers.google.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spinnaker.fullname" . }}-google
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: clouddriver
type: Opaque
data:
{{- range $index, $account := .Values.providers.google.accounts }}
  {{ $account.name }}.json: {{ $account.jsonKey | b64enc | quote }}
{{ end }}
{{ end }}