apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spinnaker.fullname" . }}-registry
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: clouddriver
type: Opaque
data:
  {{- range $index, $account := .Values.providers.docker.accounts }}
  password-{{ $account.name }}: {{ default "" $account.password | b64enc | quote }}
  {{- end }}