apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.agent-fullname" . }}
  labels:
    app: {{ template "jenkins.master-fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  ports:
    - port: {{ .Values.Agent.port }}
      targetPort: {{ .Values.Agent.port }}
      name: slavelistener
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
  type: ClusterIP
