apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lcm.fullname" . }}-destroy
data:
  destroy.json: |
    {
      "application": "{{ .Values.spinnaker.application.name }}",
      "name": "Kubernetes destroy",
      "keepWaitingPipelines": false,
      "lastModifiedBy": "anonymous",
      "limitConcurrent": true,
      "parallel": true,
      "parameterConfig": [
        {
          "name": "ENV_ID"
        }
      ],
      "stages": [
        {
          "account": "local",
          "annotations": {},
          "application": "{{ .Values.spinnaker.application.name }}",
          "cloudProvider": "kubernetes",
          "cloudProviderType": "kubernetes",
          "container": {
            "args": [],
            "command": [
              "sh",
              "-cex",
              "ANSIBLE_CONFIG=/opt/playbooks/workflow/ansible.cfg ansible-playbook -e env_id=\"${ parameters.ENV_ID }\" /opt/playbooks/workflow/destroy.yml"
            ],
            "envVars": [],
            "imageDescription": {
              "account": "dockerhub",
              "fromTrigger": false,
              "organization": "k8sprayorg",
              "registry": "index.docker.io",
              "repository": "k8sprayorg/ansible",
              "tag": "2.3.0.0"
            },
            "name": "job",
            "volumeMounts": []
          },
          "labels": {},
          "name": "Destroy nodes",
          "namespace": "{{ .Release.Namespace }}",
          "refId": "1",
          "requisiteStageRefIds": [],
          "type": "runJob",
          "volumeSources": []
        }
      ],
      "triggers": []
    }