apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spinnaker.fullname" . }}-tests
data:
  run.sh: |-
    @test "Testing Spinnaker UI is accessible" {
      curl --retry 12 --retry-delay 10 {{ template "spinnaker.fullname" . }}-deck:{{ .Values.ui.port }}
    }