apiVersion: v1
kind: Service
metadata:
  name: {{ template "spinnaker.fullname" . }}-clouddriver
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: clouddriver
spec:
  ports:
    - port: 7002
  selector:
    app: {{ template "spinnaker.fullname" . }}
    component: clouddriver
