apiVersion: v1
kind: Service
metadata:
  name: {{ template "spinnaker.fullname" . }}-deck
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: deck
{{- if .Values.ui.service.annotations }}
  annotations:
{{ toYaml .Values.ui.service.annotations | indent 4}}
{{- end }}
spec:
  ports:
  - port: {{ .Values.ui.port }}
    name: webui
    {{- if eq .Values.ui.service.type "NodePort" }}
    {{- if .Values.ui.service.nodePort }}
    nodePort: {{ .Values.ui.service.nodePort }}
    {{- end -}}
    {{- end }}
  selector:
    app: {{ template "spinnaker.fullname" . }}
    component: deck
  type: "{{ .Values.ui.service.type }}"
{{- if eq .Values.ui.service.type "LoadBalancer" }}
  {{- if .Values.ui.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.ui.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.ui.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.ui.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}
