apiVersion: v1
kind: Service
metadata:
  name: {{ template "spinnaker.fullname" . }}-echo
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: echo
spec:
  ports:
    - port: 8089
  selector:
    app: {{ template "spinnaker.fullname" . }}
    component: echo
