apiVersion: v1
kind: Service
metadata:
  name: {{ template "spinnaker.fullname" . }}-front50
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: front50
spec:
  ports:
    - port: 8080
  selector:
    app: {{ template "spinnaker.fullname" . }}
    component: front50
