apiVersion: v1
kind: Service
metadata:
  name: {{ template "spinnaker.fullname" . }}-gate
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: gate
spec:
  ports:
    - port: 8084
  selector:
    app: {{ template "spinnaker.fullname" . }}
    component: gate
