apiVersion: v1
kind: Service
metadata:
  name: {{ template "spinnaker.fullname" . }}-orca
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: orca
spec:
  ports:
    - port: 8083
  selector:
    app: {{ template "spinnaker.fullname" . }}
    component: orca
