apiVersion: v1
kind: Service
metadata:
  name: {{ template "spinnaker.fullname" . }}-rosco
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: rosco
spec:
  ports:
    - port: 8087
  selector:
    app: {{ template "spinnaker.fullname" . }}
    component: rosco
