---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: clickhouse-server
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: clickhouse
    spec:
      initContainers:
      - name: chown
        image: alpine:3.6
        command: ['/bin/sh', '-c', 'chown 105:106 -R /var/lib/clickhouse']
        volumeMounts:
        - name: data
          mountPath: /var/lib/clickhouse
      containers:
      - name: clickhouse
        image: flant/loghouse-clickhouse:{{ default .Chart.Version .Values.version }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 8123
        - name: native
          containerPort: 9000
        env:
        - name: CLICKHOUSE_SERVER
          value: {{ .Values.clickhouse.server | quote }}
        - name: CLICKHOUSE_PORT
          value: {{ .Values.clickhouse.port | quote }}
        - name: CLICKHOUSE_USER
          value: {{ .Values.clickhouse.user | quote }}
        - name: CLICKHOUSE_PASS
          value: {{ .Values.clickhouse_pass_original | quote }}
        - name: CLICKHOUSE_DB
          value: {{ .Values.clickhouse.db | quote }}
        - name: K8S_LOGS_TABLE
          value: {{ .Values.clickhouse.table | quote }}
        livenessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 30
          tcpSocket:
            port: 9000
        readinessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 5
          tcpSocket:
            port: 9000
        resources:
{{ toYaml .Values.clickhouse.resources | indent 10 }}
        volumeMounts:
          - name: data
            mountPath: /var/lib/clickhouse/
          - name: config-volume
            mountPath: /etc/clickhouse-server/
      volumes:
        - name: data
          emptyDir: {}
        - name: config-volume
          configMap:
            name: clickhouse-config
{{- if .Values.tolerations }}
      tolerations:
      - operator: {{ .Values.tolerations.operator | quote }}
        key: {{ .Values.tolerations.key | quote }}
{{- if .Values.tolerations.value }}
        value: {{ .Values.tolerations.value | quote }}
{{- end }}
{{- if .Values.tolerations.effect }}
        effect: {{ .Values.tolerations.effect | quote }}
{{- end }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
{{- end }}

