{{- if .Values.minio.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-create-bucket"
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: minio
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: {{ template "spinnaker.fullname" . }}
        component: minio
    spec:
      restartPolicy: OnFailure
      containers:
      - name: post-install-job
        image: "minio/mc:RELEASE.2017-06-15T03-38-43Z"
        command:
        - sh
        - -c
        - "mc config host add {{.Release.Name}}-minio {{ template "spinnaker.minio-address" . }} {{ .Values.minio.accessKey }} {{ .Values.minio.secretKey }} S3v4 && mc mb -p {{.Release.Name}}-minio/spinnaker"
{{- end }}
