apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "spinnaker.fullname" . }}-deck
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: deck
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/spinnaker-config.yaml") . | sha256sum }}
      labels:
        app: {{ template "spinnaker.fullname" . }}
        component: deck
    spec:
      containers:
        - image: {{ .Values.images.deck }}
          name: deck
          env:
            - name: API_HOST
              value: http://{{ template "spinnaker.fullname" . }}-gate:8084/
            - name: DECK_HOST
              value: "0.0.0.0"
            - name: DECK_PORT
              value: "{{ .Values.ui.port }}"
          ports:
            - containerPort: {{ .Values.ui.port }}
              name: deck
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "spinnaker.fullname" . }}-spinnaker-config
      volumes:
        - name: {{ template "spinnaker.fullname" . }}-spinnaker-config
          configMap:
            name: {{ template "spinnaker.fullname" . }}-spinnaker-config
