apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "spinnaker.fullname" . }}-echo
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: echo
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/spinnaker-config.yaml") . | sha256sum }}
      labels:
        app: {{ template "spinnaker.fullname" . }}
        component: echo
    spec:
      containers:
        - image: {{ .Values.images.echo }}
          name: echo
          ports:
            - containerPort: 8089
              name: echo
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "spinnaker.fullname" . }}-spinnaker-config
          readinessProbe:
            httpGet:
              path: /env
              port: 8089
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: {{ template "spinnaker.fullname" . }}-spinnaker-config
          configMap:
            name: {{ template "spinnaker.fullname" . }}-spinnaker-config
