apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "spinnaker.fullname" . }}-front50
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: front50
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/spinnaker-config.yaml") . | sha256sum }}
      labels:
        app: {{ template "spinnaker.fullname" . }}
        component: front50
    spec:
      containers:
        - image: {{ .Values.images.front50 }}
          name: front50
          ports:
            - containerPort: 8080
              name: front50
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "spinnaker.fullname" . }}-spinnaker-config
            - mountPath: /root/.aws
              name: {{ template "spinnaker.fullname" . }}-minio-config
            {{ if .Values.gcs.enabled }}
            - mountPath: /root/.kube
              name: {{ template "spinnaker.fullname" . }}-gcs
            {{ end }}
          readinessProbe:
            httpGet:
              path: /env
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: {{ template "spinnaker.fullname" . }}-spinnaker-config
          configMap:
            name: {{ template "spinnaker.fullname" . }}-spinnaker-config
        - name: {{ template "spinnaker.fullname" . }}-minio-config
          configMap:
            name: {{ template "spinnaker.fullname" . }}-minio-config
        {{ if .Values.gcs.enabled }}
        - name: {{ template "spinnaker.fullname" . }}-gcs
          secret:
            secretName: {{ template "spinnaker.fullname" . }}-gcs
        {{ end }}
