apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "spinnaker.fullname" . }}-igor
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: igor
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/spinnaker-config.yaml") . | sha256sum }}
      labels:
        app: {{ template "spinnaker.fullname" . }}
        component: igor
    spec:
      containers:
        - image: {{ .Values.images.igor }}
          name: igor
          ports:
            - containerPort: 8088
              name: igor
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "spinnaker.fullname" . }}-spinnaker-config
          readinessProbe:
            httpGet:
              path: /env
              port: 8088
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
      - name: {{ template "spinnaker.fullname" . }}-spinnaker-config
        configMap:
          name: {{ template "spinnaker.fullname" . }}-spinnaker-config
