apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "spinnaker.fullname" . }}-rosco
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: rosco
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/spinnaker-config.yaml") . | sha256sum }}
      labels:
        app: {{ template "spinnaker.fullname" . }}
        component: rosco
    spec:
      containers:
        - image: {{ .Values.images.rosco }}
          name: rosco
          ports:
            - containerPort: 8087
              name: rosco
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "spinnaker.fullname" . }}-spinnaker-config
            - mountPath: /usr/bin/docker
              name: docker-bin
            - mountPath: /var/run/docker.sock
              name: docker-sock
            {{ if .Values.providers.google.enabled }}
            - mountPath: /root/.google
              name: google
            {{ end }}
          readinessProbe:
            httpGet:
              path: /env
              port: 8087
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: {{ template "spinnaker.fullname" . }}-spinnaker-config
          configMap:
            name: {{ template "spinnaker.fullname" . }}-spinnaker-config
        - name: docker-bin
          hostPath:
            path: /usr/bin/docker
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        {{ if .Values.providers.google.enabled }}
        - name: google
          secret:
            secretName: {{ template "spinnaker.fullname" . }}-google
        {{ end }}
