apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "spinnaker.fullname" . }}-clouddriver
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "spinnaker.fullname" . }}-clouddriver