---
apiVersion: v1
kind: Service
metadata:
  name: loghouse
spec:
  selector:
    component: loghouse

  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    targetPort: 80
    protocol: TCP
